### ISSUE TITLE
Set runtime stdout to pod's log files

### ISSUE THREAD

**Issue by sashayakovtseva** [sylabs/singularity-cri#314]
Compare: k8s+docker and k8s+singularity amd64 clusters.

Pod to create:
```
apiVersion: v1
kind: Pod
metadata:
  name: hello-arm
spec:
  containers:
    - name: arm-image
      image: nginx@sha256:c4b2169cae2fe47e82bc9ebcd537afc29ae1f2ee54402a8ebdff76e5e1f4a150
      ports:
        - containerPort: 80
```

Both result in `CrashLoopBackOff`, but when doing `kubectl logs hello-arm`:
docker: `standard_init_linux.go:207: exec user process caused "exec format error"`
singularity: `failed to open log file "/var/log/pods/default_hello-arm_a0c65cce-5fc3-4666-9a6e-8f47726db92e/arm-image/2.log": open /var/log/pods/default_hello-arm_a0c65cce-5fc3-4666-9a6e-8f47726db92e/arm-image/2.log: no such file or directory`

Maybe it is resonable to redirect runtime output to log files so that it is easier for user to understand why pod fails to start? Right now the only option is to look into syslog.
