### ISSUE TITLE
Container's stderr is not populated in logs 

### ISSUE THREAD

**Issue by sashayakovtseva** [sylabs/singularity-cri#347]
What are the steps to reproduce this issue?
-------------------------------------------
1. Launch pod without allocated tty
2. Start following logs

```
apiVersion: v1
kind: Pod
metadata:
  name: int
spec:
  containers:
    - name: int
      image: cloud.sylabs.io/sashayakovtseva/test/test-info:interactive
      args: ["--interval", "1s"]
```

What happens?
-------------
After some period of time stderr entries no longer appear.

What were you expecting to happen?
----------------------------------
Stderr entries appear as usual.

Environment?
----------------------------------------
**OS distribution and version:** Linux node-1 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**go version:** go version go1.12.6 linux/amd64

**Singularity-CRI version:** v1.0.0-beta.4

**Singularity version:** 3.3.0-rc.1.461.g4a5397cdb

**Kubernetes version:** 1.15.1
